spring:
  application:
    name: RowayShop
  servlet:
    multipart:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/roway
    username: postgres
    password: Vanbui262004@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: V0qfFwSH4RKrjG7F60Mm5NklyLTy2DsdDhRU03G2A1s=
      expiration: 3600000 # Thời gian hết hạn (1 ngày)
